config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pets', to: 'pets#index', as: :pets
  get 'pets/new', to: 'pets#new', as: :new_pet
  get 'pets/:id', to: 'pets#show', as: :pet
  post 'pets', to: 'pets#create'
  get 'pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch 'pets/:id', to: 'pets#update'
  delete 'pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ['dog', 'cat', 'crocodile', 'snake', 'fish', 'tiger']
  validates :name, presence: true
  validates :address, presence: true
  validates :color, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :found_on, :color, :age, :species)
  end

  def find_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetFinder360</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :age %>
  <%= f.input :color, as: :color %>
  <%= f.input :found_on, html5: true %>
  <%= f.input :species, collection: Pet::SPECIES %>
<% end %>

app/views/pets/edit.html.erb
<%= render 'form' %>

app/views/pets/index.html.erb
<h1>All pets</h1>
<% @pets.each do |pet| %>
  <p><%= link_to pet.name, pet_path(pet.id) %></p>
  <hr>
<% end %>

app/views/pets/new.html.erb
<%= render 'form' %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p><%= @pet.address %></p>
<p><%= @pet.found_on %></p>
<p><%= @pet.species %></p>
<p><%= @pet.age %></p>
<div style="width: 100px; height: 50px; background-color: <%= @pet.color %>"></div>
<%= link_to 'back', pets_path, class:'link' %>
<%= link_to 'edit', edit_pet_path(@pet.id) %>
<%= link_to 'delete', pet_path(@pet.id), method: :delete, data: { confirm: 'Are you sure you want to destroy your pet?' } %>